export const Data = [
  {
    _id: "1",
    name: "things fall apart",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cup_idatat non pro_ident, sunt in culpa qui officia deserunt mollit anim _id est laborum",
    category: "Female Dress",
    subCategory: "Gown",
    rating: 1.5,
    price: 50.4,
    bestSeller: true,
    date: 1716634545555,
    brand: "Nike",
    countInSock: 14,
    numReviews: 10,
    image: "/images/items/project1.jpg",
  },
  {
    _id: "2",
    name: "Arrow of God",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cup_idatat non pro_ident, sunt in culpa qui officia deserunt mollit anim _id est laborum",
    category: "Unisex",
    subCategory: "Truoser",
    rating: 0.5,
    price: 500.4,
    bestSeller: true,
    date: 1716634545555,
    brand: "Nike",
    countInSock: 0,
    numReviews: 12,
    image: "/images/items/project2.jpg",
  },
  {
    _id: "3",
    name: "lucas life",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cup_idatat non pro_ident, sunt in culpa qui officia deserunt mollit anim _id est laborum",
    category: "Men's Wear",
    subCategory: "Tshirt",
    rating: 0.2,
    price: 51.4,
    bestSeller: true,
    date: 1716634545555,
    brand: "Nike",
    countInSock: 20,
    numReviews: 15,
    image: "/images/items/project3.jpg",
  },
  {
    _id: "4",
    name: "things fall in shape",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cup_idatat non pro_ident, sunt in culpa qui officia deserunt mollit anim _id est laborum",
    category: "life drama",
    subCategory: "ken",
    rating: 1.0,
    price: 40.1,
    bestSeller: true,
    date: 1716634545555,
    brand: "Nike",
    countInSock: 18,
    numReviews: 5,
    image: "/images/items/project4.jpg",
  },
  {
    _id: "5",
    name: "game of throne",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cup_idatat non pro_ident, sunt in culpa qui officia deserunt mollit anim _id est laborum",
    category: "prose",
    subCategory: "zion",
    rating: 0.7,
    price: 20.55,
    bestSeller: false,
    date: 1716634545555,
    brand: "Nike",
    countInSock: 14,
    numReviews: 28,
    image: "/images/items/project5.jpg",
  },
  {
    _id: "6",
    name: "blindspot",
    description:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cup_idatat non pro_ident, sunt in culpa qui officia deserunt mollit anim _id est laborum",
    category: "drama",
    subCategory: "jane",
    rating: 0.3,
    price: 100.0,
    bestSeller: false,
    date: 1716634545555,
    brand: "Nike",
    countInSock: 0,
    numReviews: 30,
    image: "/images/items/project2.jpg",
  },
];
